export type AmigoMetadataType = {
  amigo: number;
  glasses: string;
  head: string;
  accesory: string;
  body: string;
  background: string;
};

export const AMIGOS_METADATA: AmigoMetadataType[] = [
  {
    amigo: 0,
    glasses: "square-yellow-orange-multi",
    head: "burrito",
    accesory: "hola",
    body: "orange",
    background: "warm",
  },
  {
    amigo: 1,
    glasses: "square-honey",
    head: "calaverita",
    accesory: "cuerdas-de-sudadera",
    body: "hotbrown",
    background: "warm",
  },
  {
    amigo: 2,
    glasses: "square-yellow-orange-multi",
    head: "cacomixtle",
    accesory: "gafete",
    body: "yellow",
    background: "cool",
  },
  {
    amigo: 3,
    glasses: "square-black",
    head: "iguana",
    accesory: "corbata-negra",
    body: "grayscale-9",
    background: "warm",
  },
  {
    amigo: 4,
    glasses: "square-blue",
    head: "jaguar",
    accesory: "lineas-olivo",
    body: "slimegreen",
    background: "warm",
  },
  {
    amigo: 5,
    glasses: "square-orange",
    head: "llama",
    accesory: "tejido-sucio",
    body: "gunk",
    background: "cool",
  },
  {
    amigo: 6,
    glasses: "square-green-blue-multi",
    head: "ajolote",
    accesory: "tortuga",
    body: "purple",
    background: "cool",
  },
  {
    amigo: 7,
    glasses: "square-teal",
    head: "platano-frito",
    accesory: "escalera-de-arcoiris",
    body: "bege-bsod",
    background: "warm",
  },
  {
    amigo: 8,
    glasses: "square-fullblack",
    head: "aguacate",
    accesory: "cuadricula-azul",
    body: "blue-sky",
    background: "cool",
  },
  {
    amigo: 9,
    glasses: "square-black-rgb",
    head: "sombrero",
    accesory: "pepe",
    body: "grayscale-8",
    background: "cool",
  },
  {
    amigo: 10,
    glasses: "square-black-rgb",
    head: "arepa",
    accesory: "tucan",
    body: "orange",
    background: "warm",
  },
  // 10
  {
    amigo: 11,
    glasses: "square-teal",
    head: "burrito",
    accesory: "cara-feliz-invertida",
    body: "darkpink",
    background: "warm",
  },
  {
    amigo: 12,
    glasses: "square-black-eyes-red",
    head: "llama",
    accesory: "queso",
    body: "green",
    background: "warm",
  },
  {
    amigo: 13,
    glasses: "warm",
    head: "jaguar",
    accesory: "cc0",
    body: "red",
    background: "cool",
  },
  {
    amigo: 14,
    glasses: "square-grey-light",
    head: "sombrero",
    accesory: "cara-seria",
    body: "rust",
    background: "cool",
  },
  {
    amigo: 15,
    glasses: "deep-teal",
    head: "ajolote",
    accesory: "lineas-rojas",
    body: "peachy-a",
    background: "cool",
  },
  {
    amigo: 16,
    glasses: "square-red",
    head: "platano-frito",
    accesory: "cuadricula-ancha-negra",
    body: "teal-light",
    background: "warm",
  },
  {
    amigo: 17,
    glasses: "square-honey",
    head: "llama",
    accesory: "vaca",
    body: "darkbrown",
    background: "warm",
  },
  {
    amigo: 18,
    glasses: "square-yellow-orange-multi",
    head: "calaverita",
    accesory: "boleto-metro",
    body: "orange-yellow",
    background: "cool",
  },
  {
    amigo: 19,
    glasses: "square-black-eyes-red",
    head: "sombrero",
    accesory: "DAO",
    body: "teal",
    background: "warm",
  },
  {
    amigo: 20,
    glasses: "square-yellow-saturated",
    head: "burrito",
    accesory: "fantasma",
    body: "blue-sky",
    background: "warm",
  },
  // 20
  {
    amigo: 21,
    glasses: "square-fullblack",
    head: "cacomixtle",
    accesory: "cool",
    body: "grayscale-8",
    background: "cool",
  },
  {
    amigo: 22,
    glasses: "square-orange",
    head: "aguacate",
    accesory: "habanero",
    body: "darkpink",
    background: "cool",
  },
  {
    amigo: 23,
    glasses: "square-red",
    head: "iguana",
    accesory: "BD",
    body: "gunk",
    background: "warm",
  },
  {
    amigo: 24,
    glasses: "square-fullblack",
    head: "iguana",
    accesory: "lineas-y-cuadros",
    body: "grayscale-7",
    background: "cool",
  },
  {
    amigo: 25,
    glasses: "hip-rose",
    head: "calaverita",
    accesory: "nuns",
    body: "teal",
    background: "warm",
  },
  {
    amigo: 26,
    glasses: "square-yellow-saturated",
    head: "cacomixtle",
    accesory: "perro",
    body: "peachy-B",
    background: "cool",
  },
  {
    amigo: 27,
    glasses: "square-orange",
    head: "ajolote",
    accesory: "ok",
    body: "yellow",
    background: "warm",
  },
  {
    amigo: 28,
    glasses: "grass",
    head: "llama",
    accesory: "lineas-rosas",
    body: "darkbrown",
    background: "warm",
  },
  {
    amigo: 29,
    glasses: "square-magenta",
    head: "arepa",
    accesory: "arepa",
    body: "darkpink",
    background: "warm",
  },
  {
    amigo: 30,
    glasses: "square-red",
    head: "iguana",
    accesory: "hongo",
    body: "yellow",
    background: "cool",
  },
  // 30
  {
    amigo: 31,
    glasses: "square-guava",
    head: "burrito",
    accesory: "gaviota",
    body: "peachy-a",
    background: "warm",
  },
  {
    amigo: 32,
    glasses: "hip-rose",
    head: "ajolote",
    accesory: "trebol",
    body: "orange-yellow",
    background: "cool",
  },
  {
    amigo: 33,
    glasses: "square-honey",
    head: "jaguar",
    accesory: "alien",
    body: "darkbrown",
    background: "warm",
  },
  {
    amigo: 34,
    glasses: "square-red",
    head: "dalmata",
    accesory: "moscas",
    body: "green",
    background: "cool",
  },
  {
    amigo: 35,
    glasses: "square-black-eyes-red",
    head: "limon",
    accesory: "patito",
    body: "magenta",
    background: "warm",
  },
  {
    amigo: 36,
    glasses: "square-yellow-orange-multi",
    head: "navegador",
    accesory: "nuns",
    body: "purple",
    background: "cool",
  },
  {
    amigo: 37,
    glasses: "square-blue",
    head: "piñata",
    accesory: "pop",
    body: "bluegrey",
    background: "warm",
  },
  {
    amigo: 38,
    glasses: "hip-rose",
    head: "piñata",
    accesory: "ñ",
    body: "orange-yellow",
    background: "warm",
  },
  {
    amigo: 39,
    glasses: "square-orange",
    head: "arpia",
    accesory: "cuerdas-de-sudadera",
    body: "green",
    background: "cool",
  },
  {
    amigo: 40,
    glasses: "square-teal",
    head: "raton",
    accesory: "cuadricula-chica-magenta",
    body: "orange",
    background: "cool",
  },
  // 40
  {
    amigo: 41,
    glasses: "square-pink-purple-multi",
    head: "pantera",
    accesory: "degradado-discoteca",
    body: "blue-sky",
    background: "warm",
  },
  {
    amigo: 42,
    glasses: "square-blue",
    head: "aguila",
    accesory: "cuadricula-ancha-negra",
    body: "blue-sky",
    background: "warm",
  },
  {
    amigo: 43,
    glasses: "square-black-eyes-red",
    head: "tapir-chido",
    accesory: "disco-de-vinil",
    body: "slimegreen",
    background: "cool",
  },
  {
    amigo: 44,
    glasses: "square-black",
    head: "pantera",
    accesory: "corbata-negra",
    body: "computerblue",
    background: "warm",
  },
  {
    amigo: 45,
    glasses: "square-pink-purple-multi",
    head: "dalmata",
    accesory: "vaca",
    body: "darkpink",
    background: "cool",
  },
  {
    amigo: 46,
    glasses: "square-green-blue-multi",
    head: "limon",
    accesory: "habanero",
    body: "orange",
    background: "warm",
  },
  {
    amigo: 47,
    glasses: "square-red",
    head: "tijeras",
    accesory: "bomba",
    body: "red",
    background: "cool",
  },
  {
    amigo: 48,
    glasses: "square-guava",
    head: "pantera",
    accesory: "lineas-verdes",
    body: "peachy-B",
    background: "cool",
  },
  {
    amigo: 49,
    glasses: "square-blue-med-saturated",
    head: "dalmata",
    accesory: "fantasma",
    body: "yellow",
    background: "cool",
  },
  {
    amigo: 50,
    glasses: "square-fullblack",
    head: "tapir-chido",
    accesory: "palmera",
    body: "cold",
    background: "warm",
  },
  // 10
  {
    amigo: 51,
    glasses: "square-yellow-saturated",
    head: "cacomixtle",
    accesory: "trebol",
    body: "slimegreen",
    background: "warm",
  },
  {
    amigo: 52,
    glasses: "square-grey-light",
    head: "navegador",
    accesory: "tejido-bicolor",
    body: "grayscale-7",
    background: "cool",
  },
  {
    amigo: 53,
    glasses: "square-yellow-saturated",
    head: "pantera",
    accesory: "bomba",
    body: "grayscale-8",
    background: "cool",
  },
  {
    amigo: 54,
    glasses: "square-red",
    head: "ajolote",
    accesory: "degradado-pride",
    body: "orange-yellow",
    background: "cool",
  },
  {
    amigo: 55,
    glasses: "square-red",
    head: "sombrero",
    accesory: "gallina",
    body: "red",
    background: "warm",
  },
  {
    amigo: 56,
    glasses: "square-fullblack",
    head: "limon",
    accesory: "nuns",
    body: "green",
    background: "warm",
  },
  {
    amigo: 57,
    glasses: "square-black",
    head: "burrito",
    accesory: "corbata-negra",
    body: "grayscale-7",
    background: "warm",
  },
  {
    amigo: 58,
    glasses: "square-fullblack",
    head: "arepa",
    accesory: "cuadricula-ancha-negra",
    body: "gold",
    background: "cool",
  },
  {
    amigo: 59,
    glasses: "no-disponible",
    head: "no-disponible",
    accesory: "no-disponible",
    body: "no-disponible",
    background: "cool",
  },
  {
    amigo: 60,
    glasses: "no-disponible",
    head: "no-disponible",
    accesory: "no-disponible",
    body: "no-disponible",
    background: "warm",
  },
  // 60
  {
    amigo: 61,
    glasses: "no-disponible",
    head: "no-disponible",
    accesory: "no-disponible",
    body: "no-disponible",
    background: "cool",
  },
  //   {
  //     amigo: 62,
  //     glasses: "",
  //     head: "",
  //     accesory: "",
  //     body: "",
  //     background: "",
  //   },
];
